In [1]:
%matplotlib inline

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv("C:/Users/Weng/Desktop/Web economics/Dataset/train.csv")
#df_v = pd.read_csv("C:/Users/Weng/Desktop/Web economics/Dataset/validation.csv")
#df_test = pd.read_csv("C:/Users/Weng/Desktop/Web economics/Dataset/test.csv")

In [4]:
df.head()

,click,weekday,hour,bidid,logtype,userid,useragent,IP,region,city,...,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
0,0,1,14,fdfae6789b787899f1b875de3ab8b21a,1,u_Vh1OPkFv3q5CFdR,windows_ie,180.107.112.*,80,85,...,60,1,0,5,612599432d200b093719dd1f372f7a30,300,54,bebefa5efe83beee17a3d245e7c5085b,1458,"13866,10063"
1,0,2,20,372883147cdefbc495fb5082f79dde9b,1,u_VhkRL6dCOTLsq-c,windows_chrome,125.120.199.*,94,95,...,250,1,0,5,8dff45ed862a740986dbe688aafee7e5,249,42,15b749127478946f161a54dc0dad27c8,3476,"10063,10111"
2,0,5,9,2912cb5947e1fad450e2473c2f61ef75,1,u_VhkyORMrD8TP3GL,windows_ie,120.196.64.*,216,217,...,280,0,1,0,77819d3e0b3467fe5c7b16d68ad923a1,300,76,bebefa5efe83beee17a3d245e7c5085b,1458,10063
3,0,2,20,d7b7d61d1e50e1d27d210928d28a9b61,1,u_VhkyLRqVL2a4eWL,windows_ie,219.131.122.*,216,221,...,90,0,0,162,7184c9560e68e977187e67e45a4f3198,238,182,0f951a030abdaedd733ee8d114ce2944,3427,"10077,10111"
4,0,6,9,657d317dc4045bb79c2652abbea07530,1,u_Vh1zOJuQOtTCBgL,windows_chrome,123.190.78.*,40,48,...,90,0,1,0,c938195f9e404b4f38c7e71bf50263e5,238,34,a3becb967c015e9acb5e72f22b100ef8,3476,"10031,13042,10006,10057,13866,10063,14273,1005..."

In [5]:
#df_predict = pd.read_csv("C:/Users/Weng/Desktop/Web economics/Github/Web-Economics-master/click_pred.csv")

In [6]:
#df_bidprice = pd.read_csv("C:/Users/Weng/Desktop/Web economics/Github/Web-Economics-master/out.csv")

In [7]:
#df_v[df_v.bidid == 'd939cd3025fba6ee162860e5cb4fad21']

In [8]:
#df_v.ix[df_predict[df_predict[' click'] == 1].index].click

In [9]:
#df_predict_acc = df_predict

In [10]:
#df_predict_acc['v_clicks'] = df_v.loc[df_predict[df_predict[' click'] == 1].index, 'click']  # Locator of the index

In [11]:
#print ('Click prediction accuracy:  '+ str(round(((df_predict_acc['v_clicks'].sum() / df_predict_acc[' click'].sum())*100),3)))

#### Logistic regression predicts the probability of yes of no ?

In [12]:
#df_predict.head()

In [13]:
df.head()

,click,weekday,hour,bidid,logtype,userid,useragent,IP,region,city,...,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
0,0,1,14,fdfae6789b787899f1b875de3ab8b21a,1,u_Vh1OPkFv3q5CFdR,windows_ie,180.107.112.*,80,85,...,60,1,0,5,612599432d200b093719dd1f372f7a30,300,54,bebefa5efe83beee17a3d245e7c5085b,1458,"13866,10063"
1,0,2,20,372883147cdefbc495fb5082f79dde9b,1,u_VhkRL6dCOTLsq-c,windows_chrome,125.120.199.*,94,95,...,250,1,0,5,8dff45ed862a740986dbe688aafee7e5,249,42,15b749127478946f161a54dc0dad27c8,3476,"10063,10111"
2,0,5,9,2912cb5947e1fad450e2473c2f61ef75,1,u_VhkyORMrD8TP3GL,windows_ie,120.196.64.*,216,217,...,280,0,1,0,77819d3e0b3467fe5c7b16d68ad923a1,300,76,bebefa5efe83beee17a3d245e7c5085b,1458,10063
3,0,2,20,d7b7d61d1e50e1d27d210928d28a9b61,1,u_VhkyLRqVL2a4eWL,windows_ie,219.131.122.*,216,221,...,90,0,0,162,7184c9560e68e977187e67e45a4f3198,238,182,0f951a030abdaedd733ee8d114ce2944,3427,"10077,10111"
4,0,6,9,657d317dc4045bb79c2652abbea07530,1,u_Vh1zOJuQOtTCBgL,windows_chrome,123.190.78.*,40,48,...,90,0,1,0,c938195f9e404b4f38c7e71bf50263e5,238,34,a3becb967c015e9acb5e72f22b100ef8,3476,"10031,13042,10006,10057,13866,10063,14273,1005..."

#### Bidding model

In [14]:
#Take a quarter of the trainning set as a sample 
data_train = df.sample(frac = 0.2,random_state = 20).reset_index(drop=True)

In [233]:
def CTR_calc(data):
    Click_t_rate= "Click Through Rate= "+ str(round((np.count_nonzero(data.click.values)/data.shape[0])*100,4)) + ' %'
    return (Click_t_rate)

In [234]:
data_train.shape

(539548, 26)

In [235]:
CTR_calc(data_train)

'Click Through Rate= 0.0806 %'

In [236]:
#Dropping un-interesting columns
data_train= data_train.drop(['bidid','userid','logtype','url','urlid','keypage','bidprice','payprice'],1)

In [237]:
data_train.columns

Index(['click', 'weekday', 'hour', 'useragent', 'IP', 'region', 'city',
       'adexchange', 'domain', 'slotid', 'slotwidth', 'slotheight',
       'slotvisibility', 'slotformat', 'slotprice', 'creative', 'advertiser',
       'usertag'],
      dtype='object')

In [238]:
#Second drop- to improve performance 
#data_train = data_train.drop(['IP','domain','usertag'],1)

In [239]:
data_train.head()

,click,weekday,hour,useragent,IP,region,city,adexchange,domain,slotid,slotwidth,slotheight,slotvisibility,slotformat,slotprice,creative,advertiser,usertag
0,0,5,10,windows_ie,119.249.43.*,3,9,3,5F1RQS9rg5scFsf,News_F_Width1,1000,90,0,0,80,832b91d59d0cb5731431653204a76c0e,1458,"13042,10076,10031,10057,10075,10006,13403,1006..."
1,0,1,16,windows_ie,110.241.12.*,3,4,3,3c47edf60cc139641b6395e123a6e155,ALLINONE_F_Width1,1000,90,Na,Na,70,10734,2821,"14273,10102,10006,10110,10031,13403,10063"
2,0,0,23,windows_ie,61.146.117.*,216,230,3,7ed515fe566938ee6cfbb6ebb7ea4995,Sports_F_Upright,300,250,Na,Na,10,10722,2821,"10059,10684,10083,10024,10006,16706,10111,1005..."
3,0,1,18,windows_ie,112.15.2.*,94,104,3,3043163ba84753b4b51dd3290caeae67,tips_F_Width2,1000,90,Na,Na,50,10734,2821,null
4,0,1,3,windows_ie,223.241.165.*,106,114,3,3SCYZrn0Qo18XMB4JKTI,discuz_18316225_005,728,90,0,0,20,b90c12ed2bd7950c6027bf9c6937c48a,3386,null

### Preprocessing of data

In [240]:
#Removing strings in useragent
data_train.update(data_train['useragent'].str.replace('_ie', ''))
data_train.update(data_train['useragent'].str.replace('_firefox', ''))
data_train.update(data_train['useragent'].str.replace('_safari', ''))
data_train.update(data_train['useragent'].str.replace('_chrome', ''))
data_train.update(data_train['useragent'].str.replace('_other', ''))
data_train.update(data_train['useragent'].str.replace('_opera', ''))
data_train.update(data_train['useragent'].str.replace('_maxthon', ''))
data_train.update(data_train['useragent'].str.replace('_theworld', ''))
data_train.update(data_train['useragent'].str.replace('_sogou', ''))

#### Encoding the data

In [241]:
from sklearn.preprocessing import LabelEncoder

In [242]:
le=LabelEncoder()

In [243]:
le_ad= LabelEncoder()

In [244]:
le_ad.fit(['1458', '2821', '3386', '2261', '3476', '2259', '3358', '2997', '3427'])

LabelEncoder()

In [245]:
data_train['advertiser'] = le_ad.transform(data_train.advertiser)

In [246]:
le_user= LabelEncoder()

In [247]:
data_train['useragent']= le_user.fit_transform(data_train.useragent)

In [248]:
le_adexchange= LabelEncoder()

In [249]:
le_adexchange.fit(['3', '2', '1', 'null', '4'])

LabelEncoder()

In [250]:
data_train['slotprice'] = le.fit_transform(data_train.slotprice)

In [251]:
data_train['adexchange']= le_user.fit_transform(data_train.adexchange)

In [252]:
data_train['slotwidth']=le_user.fit_transform(data_train.slotwidth)

In [253]:
data_train['slotheight']=le_user.fit_transform(data_train.slotheight)

In [254]:
data_train['slotvisibility']=le_user.fit_transform(data_train.slotvisibility)

In [255]:
data_train['slotid']=le_user.fit_transform(data_train.slotformat)

In [256]:
data_train['slotformat']=le_user.fit_transform(data_train.slotformat)

In [257]:
data_train['city']=le_user.fit_transform(data_train.city)

In [258]:
data_train['region']=le_user.fit_transform(data_train.region)

In [259]:
data_train['creative']=le_user.fit_transform(data_train.creative)

#### delete if necessary

In [260]:
data_train['usertag']= le_user.fit_transform(data_train.usertag)

In [261]:
data_train['domain']= le_user.fit_transform(data_train.domain)

In [262]:
data_train['IP']= le_user.fit_transform(data_train.IP)

In [263]:
#third drop- to improve performance 
#data_train = data_train.drop(['slotwidth','slotheight','slotvisibility','slotformat'],1)

In [264]:
data_train.city.unique()

array([  9,   4, 224, 103, 113,  13,  75, 262, 216, 106,   1, 314, 107,
       211, 228, 124, 250, 196, 255, 105, 170,  47,   2,  97,   0, 213,
       215, 349,  78, 283, 252,  84, 202, 270, 147, 148, 198, 248, 134,
       221,  64, 310,  89, 182,  96, 350, 217, 225,  14,  55, 145, 233,
       242, 179, 153, 164, 125, 166,  12, 151, 319, 128,   7, 230, 220,
       143,  74,  30, 214,  90, 227, 281, 243, 315, 308, 136, 174,  32,
        85, 146,  98,  94, 183, 234, 155, 152,  81,  80, 363,  29, 222,
       236, 154, 360, 115, 239, 208, 311, 126,  41,  82, 264, 132,  79,
        99, 149, 210, 186, 197,   5,  83, 190,  17, 192, 200, 100,  11,
       207, 127,  88, 165, 284, 235, 282, 130, 273, 119, 185,  42, 118,
       229, 150, 176,  18, 356,  95,  52,  20, 104,  26, 307,  23, 274,
       257, 168, 256, 110, 312, 159, 265, 121, 171,   6,  92, 244, 251,
       258,  49, 204, 316, 109, 156, 218, 269,  58,  76, 291, 334, 187,
       268,  34, 101,  19, 219, 322, 237,  62,  35, 226,  45,  43, 212,
       294,  67, 133, 266, 158, 191, 161, 261, 178, 162,  33, 318, 163,
        69, 131, 116, 351,  65, 272,  28, 367, 142, 359,  10,  56, 117,
         8, 279, 317,  24, 343, 157, 140, 277,  25,  16, 241, 194, 364,
        93, 122, 201, 137, 263, 325,  48, 347,  66, 180,  71,  37,  91,
       188,  44,  31, 141,  50,  15,   3, 139, 285, 309, 286, 175, 111,
       328, 289, 177, 292, 199, 355,  86, 129, 203, 280, 189,  63,  61,
       193,  60, 160,  36, 345, 181, 246,  68,  51, 144, 287, 313, 240,
       195, 173, 353, 295,  72,  54, 365, 167, 327,  46,  38, 108, 120,
       369,  57,  21, 275,  59,  22, 112, 232, 184,  70, 135, 260, 114,
        27,  73, 254, 288, 102, 245, 259, 361, 344, 331, 172, 253,  87,
       238, 205, 320, 352, 123, 169,  40, 330, 249,  77, 276, 223, 354,
        53, 321, 138, 323, 206, 300, 329, 362, 231, 209, 358, 301, 326,
       267, 278, 346, 335, 368,  39, 247, 357, 324, 271, 290, 342, 296,
       298, 302, 293, 306, 304, 348, 297, 332, 338, 336, 303, 341, 340,
       339, 333, 299, 337, 305, 366], dtype=int64)

In [265]:
data_train

,click,weekday,hour,useragent,IP,region,city,adexchange,domain,slotid,slotwidth,slotheight,slotvisibility,slotformat,slotprice,creative,advertiser,usertag
0,0,5,10,5,98085,3,9,2,2350,0,20,3,0,0,77,95,0,159553
1,0,1,16,5,17704,3,4,2,1361,3,20,3,7,3,67,12,3,191959
2,0,0,23,5,276069,19,224,2,3519,3,7,10,7,3,7,9,3,87687
3,0,1,18,5,32310,11,103,2,680,3,20,3,7,3,47,12,3,194642
4,0,1,3,5,236229,12,113,2,1265,0,14,3,0,0,17,103,6,194642
5,0,4,17,5,266177,3,13,2,3519,3,7,10,7,3,47,25,2,61846
6,0,4,23,5,49852,8,75,1,9765,0,2,13,0,0,145,52,6,94362
7,0,4,11,5,131897,23,262,1,8488,0,7,10,1,0,2,119,8,75229
8,0,0,11,5,275785,19,216,1,3108,3,14,3,8,3,2,82,1,46805
9,0,5,13,5,140302,12,106,2,2350,0,20,3,0,0,77,96,6,171032
10,0,2,8,5,219856,1,1,1,4462,0,6,10,0,0,13,107,5,117079
11,0,4,14,5,43972,27,314,0,780,3,13,3,7,3,0,29,2,170684
12,0,3,14,5,63524,12,107,1,4462,0,0,13,2,0,36,121,6,143657
13,0,3,23,5,245900,19,216,2,2350,0,7,10,0,0,77,50,6,16343
14,0,3,0,5,77661,19,211,2,10200,0,18,3,0,0,17,2,6,187608
15,0,4,0,5,192301,19,228,0,11863,1,17,3,1,1,0,110,5,186220
16,0,1,10,5,105296,13,124,0,4554,1,9,11,2,1,0,89,0,72217
17,0,4,15,5,150676,22,250,0,297,3,7,10,7,3,0,25,2,194642
18,0,3,15,5,255664,18,196,1,6769,0,14,3,1,0,2,58,8,174016
19,0,3,22,0,160488,23,255,0,8488,1,14,3,0,1,0,92,5,110166
20,0,1,12,5,94582,19,228,1,65,3,14,3,8,3,145,82,1,71704
21,0,4,17,0,249114,12,105,4,2766,3,8,0,8,3,2,37,4,194642
22,0,4,12,5,175372,16,170,0,4554,1,9,11,2,1,0,89,0,115275
23,0,1,22,5,217887,6,47,1,9765,0,14,3,0,0,100,103,6,194642
24,0,4,13,5,24384,2,2,1,11711,0,7,10,2,0,2,99,5,23364
25,0,4,0,5,67792,11,97,0,11732,1,7,10,1,1,0,99,5,39574
26,0,1,13,5,160621,23,262,2,1059,0,20,3,0,0,67,3,8,86956
27,0,6,14,5,149150,0,0,2,1265,0,14,3,0,0,17,58,8,110314
28,0,0,10,5,184607,19,213,2,1059,0,20,3,0,0,17,96,6,194642
29,0,1,13,5,53084,19,215,2,2350,0,20,3,0,0,67,112,7,194642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539518,0,4,16,0,48527,18,196,4,3748,3,8,0,8,3,2,37,4,170991
539519,0,0,12,5,233300,16,173,0,10611,1,2,13,0,1,0,52,6,41702
539520,0,3,22,5,105002,13,125,0,11737,1,17,3,1,1,0,110,5,174484
539521,0,1,10,5,177342,23,272,1,8579,0,7,10,2,0,2,119,8,99357
539522,0,3,18,5,235872,12,119,2,2350,0,20,3,0,0,77,96,6,9940
539523,0,0,22,5,151076,19,228,1,7500,3,14,3,5,3,2,6,3,194642
539524,0,0,20,5,101898,3,4,1,9765,0,14,3,0,0,56,55,5,194642
539525,0,3,17,5,6287,3,14,2,2350,0,20,3,0,0,67,96,6,194642
539526,0,0,0,5,43847,27,308,1,1278,0,9,11,2,0,2,89,0,55092
539527,0,2,7,5,266534,8,76,1,11185,0,14,3,1,0,2,58,8,86403
539528,0,0,10,5,114722,7,57,2,757,0,20,3,0,0,17,112,7,109295
539529,0,1,5,5,5291,19,211,0,345,3,7,10,6,3,0,78,1,149620
539530,0,6,22,5,137736,1,1,1,6326,0,7,10,1,0,2,1,7,194642
539531,0,6,23,5,258597,19,213,1,8488,0,14,3,2,0,2,54,0,194642
539532,0,3,16,5,137846,1,1,1,6435,3,4,7,8,3,35,20,2,194642
539533,0,2,17,5,236934,10,84,1,8488,0,14,3,2,0,2,54,0,114513
539534,0,4,22,0,122107,16,177,4,2816,3,8,0,8,3,2,37,4,194642
539535,0,0,0,5,31191,25,283,0,8924,1,17,3,2,1,0,43,7,90813
539536,0,4,16,0,214034,12,106,4,8488,3,8,0,5,3,3,37,4,194642
539537,0,0,19,5,188448,10,84,1,8488,0,14,3,2,0,2,55,5,184032
539538,0,2,16,5,49099,22,250,0,11407,1,17,3,0,1,0,125,7,53533
539539,0,4,17,5,262733,19,222,1,9346,0,14,3,2,0,2,103,6,90813
539540,0,1,9,5,61361,1,1,2,2350,0,20,3,0,0,67,96,6,160318
539541,0,4,16,5,223010,15,149,0,11664,1,14,3,0,1,0,54,0,187077
539542,0,4,11,5,206517,9,78,0,11737,1,7,10,1,1,0,119,8,83563
539543,0,1,13,5,171721,9,78,0,7656,1,9,11,3,1,0,89,0,141141
539544,0,3,23,5,97408,15,152,2,2350,0,20,3,0,0,67,100,5,114506
539545,0,0,14,5,277083,16,177,2,2350,0,7,10,0,0,77,1,7,94460
539546,0,1,5,5,227130,23,270,1,8488,0,7,10,2,0,2,1,7,194642
539547,0,2,20,5,29665,14,138,0,6555,1,7,10,0,1,0,51,7,194642

In [266]:
data_train.columns

Index(['click', 'weekday', 'hour', 'useragent', 'IP', 'region', 'city',
       'adexchange', 'domain', 'slotid', 'slotwidth', 'slotheight',
       'slotvisibility', 'slotformat', 'slotprice', 'creative', 'advertiser',
       'usertag'],
      dtype='object')

In [268]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
data_train = pd.DataFrame(mm.fit_transform(data_train))
data_train.columns = ['click', 'weekday', 'hour', 'useragent', 'IP', 'region', 'city',
       'adexchange', 'domain', 'slotid', 'slotwidth', 'slotheight',
       'slotvisibility', 'slotformat', 'slotprice', 'creative', 'advertiser',
       'usertag']

In [269]:
#One hot encoding - arrange in order - only run once then restart because it crashes - not necessary for random forests
#data_train = pd.get_dummies(data_train, columns = ['weekday','advertiser','hour','adexchange','slotformat','slotvisibility','useragent'])# columns = ['weekday','advertiser','hour','slotheight','slotwidth']

In [270]:
#Features and gold labels
#x_feat= data_train.ix[:,1:] # might have different columns when one hot another sample
#y_targets = data_train['click']

In [271]:
#Separate the training set 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_train.ix[:,1:], data_train['click'], test_size=0.2,random_state=4)

In [272]:
y_train.shape

(431638,)

In [273]:
#Work with x_train-Bid request and y_train - clicks
X_train.head()

,weekday,hour,useragent,IP,region,city,adexchange,domain,slotid,slotwidth,slotheight,slotvisibility,slotformat,slotprice,creative,advertiser,usertag
449769,1.000000,0.913043,1.0,0.350413,0.500000,0.509485,0.25,0.759097,0.000000,0.70,0.230769,0.1,0.000000,0.007353,0.437500,0.875,0.075919
318008,0.166667,0.434783,1.0,0.794306,0.470588,0.471545,0.50,0.196570,0.000000,1.00,0.230769,0.0,0.000000,0.172794,0.875000,0.875,0.479383
411501,0.166667,1.000000,1.0,0.064466,0.088235,0.029810,0.50,0.604266,0.000000,1.00,0.230769,0.0,0.000000,0.246324,0.742188,0.000,0.478442
457142,0.500000,0.000000,1.0,0.026345,0.264706,0.211382,0.00,0.380928,0.333333,0.45,0.846154,0.2,0.333333,0.000000,0.695312,0.000,0.013995
510614,1.000000,0.478261,1.0,0.754238,0.735294,0.769648,0.25,0.970222,0.000000,0.70,0.230769,0.2,0.000000,0.007353,0.437500,0.875,0.890604

#### PCTR prediction feature engineering

In [2]:
#Using random forest classifier to predict clicks
from sklearn.ensemble import RandomForestClassifier

#### Sample split is important

#Best random forest so far 
clf = RandomForestClassifier(n_estimators=100, max_features = 2, oob_score = True, random_state = 2, 
                             min_impurity_split= 0.002, min_samples_leaf = 10,                                                         
                             min_weight_fraction_leaf= 0,min_samples_split = 10,class_weight= 'balanced_subsample')

In [ ]:
#Feel free to change the parameters
clf = RandomForestClassifier(n_estimators=100, max_features = 8, oob_score = True, random_state = 2, 
                             min_impurity_split= 0.002, min_samples_leaf = 10, 
                             min_weight_fraction_leaf= 0,min_samples_split = 10,class_weight= 'balanced_subsample') #balanced_subsample

In [440]:
%%time
clf.fit(X_train, y_train)

Wall time: 1min 46s

RandomForestClassifier(bootstrap=True, class_weight='balanced_subsample',
            criterion='gini', max_depth=None, max_features=2,
            max_leaf_nodes=1000, min_impurity_split=0.0002,
            min_samples_leaf=20, min_samples_split=15,
            min_weight_fraction_leaf=0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=2, verbose=0, warm_start=False)

In [443]:
clf_predict = clf.predict(X_test)

In [444]:
clf.oob_score_

0.99115462494034356

In [445]:
for feature, importance in zip(X_train.columns,clf.feature_importances_):
    print (feature, ":", importance)

weekday : 0.0555261127716
hour : 0.0850151466142
useragent : 0.0289440333016
IP : 0.10690612823
region : 0.0715378480668
city : 0.0956151416397
adexchange : 0.0267475811046
domain : 0.0961228855276
slotid : 0.0174492744315
slotwidth : 0.0369011579222
slotheight : 0.0344521176102
slotvisibility : 0.0378866034967
slotformat : 0.0161241541496
slotprice : 0.050764061343
creative : 0.0671801539961
advertiser : 0.0410796555961
usertag : 0.131747944199

In [446]:
acc_df = pd.DataFrame([clf_predict.transpose(),y_test], index=['Predict','Test']).transpose()

In [447]:
#Number of clicks 1 = actually predicted 
np.count_nonzero(clf_predict)

902

In [448]:
print('Number of accurate clicks: '+ str(len(acc_df[(acc_df.Predict==1)&(acc_df.Test==1)])))
print('Number of clicks: '+ str(len(acc_df[acc_df.Predict==1]))+ ' out of ' + str(len(acc_df[acc_df.Test==1])))
acc_df[(acc_df.Predict==1)&(acc_df.Test==1)]

Number of accurate clicks: 9

        Predict  Test
5637        1.0   1.0
5936        1.0   1.0
27479       1.0   1.0
31539       1.0   1.0
51515       1.0   1.0
80617       1.0   1.0
85912       1.0   1.0
91780       1.0   1.0
101797      1.0   1.0

In [427]:
acc_df[acc_df.Test == 1]

        Predict  Test
421         0.0   1.0
1001        0.0   1.0
1327        0.0   1.0
2054        0.0   1.0
2097        0.0   1.0
2885        0.0   1.0
5637        0.0   1.0
5936        1.0   1.0
11506       0.0   1.0
12392       0.0   1.0
13261       0.0   1.0
13267       0.0   1.0
13582       0.0   1.0
17813       0.0   1.0
19929       0.0   1.0
21669       0.0   1.0
22282       0.0   1.0
23559       0.0   1.0
25567       0.0   1.0
26186       0.0   1.0
27115       0.0   1.0
27449       0.0   1.0
27479       1.0   1.0
27890       0.0   1.0
30631       0.0   1.0
30633       0.0   1.0
31539       1.0   1.0
32937       0.0   1.0
33003       0.0   1.0
33518       0.0   1.0
...         ...   ...
68779       0.0   1.0
69203       0.0   1.0
73615       0.0   1.0
73626       0.0   1.0
78982       0.0   1.0
79835       0.0   1.0
80617       0.0   1.0
80985       0.0   1.0
82037       0.0   1.0
85476       0.0   1.0
85912       0.0   1.0
88164       0.0   1.0
88173       0.0   1.0
88285       0.0   1.0
90403       0.0   1.0
90800       0.0   1.0
91780       1.0   1.0
91994       0.0   1.0
94156       0.0   1.0
94864       0.0   1.0
95229       0.0   1.0
97475       0.0   1.0
97528       0.0   1.0
98303       0.0   1.0
100782      0.0   1.0
101797      0.0   1.0
102182      0.0   1.0
105317      0.0   1.0
105342      0.0   1.0
107102      0.0   1.0

[82 rows x 2 columns]

#### Cross validation

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
scores = cross_val_score(clf, data_train.ix[:,1:], data_train['click'], cv=5)